// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsfNGInGUYYxUK-3zFbx1I_Jt5krqq60w',
    appId: '1:210996918715:web:58f895375c1c958cf42c9e',
    messagingSenderId: '210996918715',
    projectId: 'automatic-ace-400605',
    authDomain: 'automatic-ace-400605.firebaseapp.com',
    storageBucket: 'automatic-ace-400605.appspot.com',
    measurementId: 'G-33M73HSNTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LhcDRzKGrHa_0wicUUTuWWvfam5-9eo',
    appId: '1:210996918715:android:81d8aae4eb2238c8f42c9e',
    messagingSenderId: '210996918715',
    projectId: 'automatic-ace-400605',
    storageBucket: 'automatic-ace-400605.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDyWS0DXCuARJ8C63mc_FErPpAbq4D8ZI',
    appId: '1:210996918715:ios:616836e40d04bd9df42c9e',
    messagingSenderId: '210996918715',
    projectId: 'automatic-ace-400605',
    storageBucket: 'automatic-ace-400605.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDyWS0DXCuARJ8C63mc_FErPpAbq4D8ZI',
    appId: '1:210996918715:ios:616836e40d04bd9df42c9e',
    messagingSenderId: '210996918715',
    projectId: 'automatic-ace-400605',
    storageBucket: 'automatic-ace-400605.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
